pages_build_output_dir = "public"
compatibility_date = "2024-01-01"
name="listes"

[vars]

[[d1_databases]]
binding = "D1_lists"
database_name = "lists"
database_id = "50e7006c-6204-4f2f-bff8-b382db7964f0"

[[durable_objects.bindings]]
name = "LIST_SYNC"
class_name = "ListSync"
script_name = "listes"
