pages_build_output_dir = "public"
compatibility_date = "2024-01-01"
name="listes"
[vars]
PUSHER_APP_ID = "your-app-id"
PUSHER_KEY = "your-app-key"
PUSHER_CLUSTER = "your-cluster"

# Add this to your .dev.vars file (not committed to git):
# PUSHER_SECRET="your-secret-key"

[[d1_databases]]
binding = "D1_lists"
database_name = "lists"
database_id = "50e7006c-6204-4f2f-bff8-b382db7964f0"

