pages_build_output_dir = "public"
compatibility_date = "2024-01-01"
name="listes"
[vars]
GOOGLE_CLIENT_ID = "your-google-client-id.apps.googleusercontent.com"
GOOGLE_REDIRECT_URI = "http://localhost:8888/auth/callback"
# For production, update GOOGLE_REDIRECT_URI to your production URL

[[d1_databases]]
binding = "D1_lists"
database_name = "lists"
database_id = "50e7006c-6204-4f2f-bff8-b382db7964f0"

